### ISSUE TITLE
Website Frontend Creation

### ISSUE THREAD

**Issue by flapanther33781** [davidjeddy/yii2-resutoran#17] opened 2017-05-14 19:37 UTC
Use screenshots in ticket #16 (closed).

**Comment by davidjeddy** [comment] 2017-05-15 14:47
Please attach the wireframe file to this ticket. TIA.

**Comment by davidjeddy** [comment] 2017-05-29 00:29
Duplicate of #10, closing.

**Closed as completed by davidjeddy** 2017-05-29 00:29 UTC
Labels: enhancement
